export const CAR_BRANDS = [
    "Toyota",
    "Hyundai",
    "Kia",
    "Nissan",
    "Chevrolet",
    "Suzuki",
    "Ford",
    "Peugeot",
    "Mitsubishi",
    "Volkswagen",
    "Mazda",
    "Honda",
    "Citroën",
    "Renault",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Great Wall",
    "MG",
    "Chery",
    "Subaru",
    "Jeep",
    "Fiat",
    "Volvo",
    "Land Rover"
];

export const CAR_MODELS: Record<string, string[]> = {
    "Toyota": ["Yaris", "Corolla", "Hilux", "RAV4", "Urban Cruiser", "Prado", "Camry", "Land Cruiser", "4Runner"],
    "Hyundai": ["Accent", "Tucson", "Santa Fe", "Elantra", "Creta", "Grand i10", "Kona", "H-1"],
    "Kia": ["Rio", "Cerato", "Sportage", "Sorento", "Morning", "Seltos", "Fronier"],
    "Nissan": ["Versa", "Sentra", "Qashqai", "X-Trail", "Frontier", "Kicks", "March", "Navara"],
    "Chevrolet": ["Sail", "Onix", "Tracker", "Colorado", "Silverado", "Spark", "Cruze", "Captiva"],
    "Suzuki": ["Swift", "Vitara", "Baleno", "Ertiga", "Dzire", "Jimny", "S-Cross"],
    "Ford": ["F-150", "Ranger", "Explorer", "Territory", "Mustang", "EcoSport", "Escape"],
    "Peugeot": ["208", "3008", "5008", "Partner", "2008", "Expert"],
    "Mitsubishi": ["L200", "Montero", "Outlander", "ASX", "Eclipse Cross", "Mirage"],
    "Volkswagen": ["Gol", "Polo", "T-Cross", "Tiguan", "Amarok", "Vento", "Jetta"],
    "Mazda": ["CX-5", "CX-30", "CX-3", "Mazda 3", "Mazda 6", "BT-50"],
    "Great Wall": ["Poer", "Wingle 5", "Wingle 7", "Haval H6", "Haval Jolion"],
    "MG": ["MG3", "MG ZS", "MG ZX", "MG HS", "MG 5"],
    "Chery": ["Tiggo 2", "Tiggo 3", "Tiggo 7", "Tiggo 8"],
    "Subaru": ["Forester", "XV", "Outback", "Impreza", "WRX"],
    "Jeep": ["Grand Cherokee", "Wrangler", "Renegade", "Compass"],
    "Fiat": ["Fiorino", "Cronos", "Pulse", "Toro"],
    "Volvo": ["XC60", "XC90", "XC40"],
    "Renault": ["Duster", "Symbol", "Kwid", "Oroch", "Koleos"]
};
